# Generated by Django 5.1.5 on 2025-02-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='borading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='end.station'),
        ),
    ]
