# Generated by Django 5.1.5 on 2025-02-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end', '0002_alter_bus_borading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='borading',
            new_name='boarding',
        ),
    ]
