# Generated by Django 5.1.5 on 2025-02-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchbus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='end.bus')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='end.bus')),
            ],
        ),
    ]
