# Generated by Django 5.1.5 on 2025-02-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('busses', models.ManyToManyField(blank=True, related_name='passanger', to='busses.busses')),
            ],
        ),
    ]
